apiVersion: batch/v1
kind: Job
metadata:
  generation: 1
  labels:
    app: oes
  name: oes-autoconfigure
  namespace: opsmx-argo
spec:
  template:
    spec:
      containers:
      - command:
        - sh
        - /tmp/config/datasource-api.sh
        image: quay.io/opsmxpublic/awsgit:v2-openssh-javalibs
        imagePullPolicy: IfNotPresent
        name: auto-configure
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/config
          name: autoconfigure
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: oes-auto-configure-opsmx-argo
      serviceAccountName: oes-auto-configure-opsmx-argo
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: oes-autoconfigure
        name: autoconfigure
