---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: opsmxproject
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: '!default'
    server: '*'
  - name: '*'
    namespace: '!cert-manager'
    server: '*'
  - name: '*'
    namespace: '!ingress-nginx'
    server: '*'
  - name: '*'
    namespace: '!kube-node-lease'
    server: '*'
  - name: '*'
    namespace: '!kube-public'
    server: '*'
  - name: '*'
    namespace: '!kube-system'
    server: '*'
  sourceRepos:
  - '*'
status: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
spec:
  destination:
    namespace: opsmx-argo
    name: in-cluster
    server: ''
  source:
    path: sampleapps
    repoURL: 'git@github.com:OpsMx/isd-sample-apps.git'
    targetRevision: HEAD
  project: opsmxproject
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
