apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-deploy
spec:
  destination:
    namespace: argo-sampleapp
    server: https://kubernetes.default.svc
  project: opsmxproj
  source:
    path: sampledeployment
    repoURL: git@github.com:OpsMx/argo-sample-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

