apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canary-rollout
spec:
  destination:
    namespace: opsmx-argo
    server: https://kubernetes.default.svc
  project: opsmxproj
  source:
    path: canary-rollout
    repoURL: https://github.com/OpsMx/isd-sample-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

