apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-rollouts-demo
spec:
  destination:
    namespace: opsmx-argo
    server: https://kubernetes.default.svc
  project: opsmxproject
  source:
    path: prometheus-rollouts-demo
    repoURL: git@github.com:OpsMx/isd-sample-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

