apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sampleapp-namespace
spec:
  destination:
    namespace: opsmx-argo-sample
    server: https://kubernetes.default.svc
  project: opsmxproj
  source:
    path: sampleapps-opsmxproj/namespace
    repoURL: git@github.com:OpsMx/argo-sample-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
